### PR TITLE
Update autocomplete for multiqueries for M1

### PR DESCRIPTION
**Pull request by bsuravech**

### CODE REVIEW

**Comment by bsuravech** [comment]
Very weird. I tested the new bundle locally and saw strange behavior of the queries call running twice:

First try failed because the endpoint is `http`:
Screenshot 2021-02-10 at 22 28 35

The second one and the successful one because it's in `https`:
Screenshot 2021-02-10 at 22 28 40

Is there a dependency issue with the helper perhaps? @Haroenv 

Not urgent but very curious.

**Comment by Haroenv** [comment]
307 seems like something the engine is doing, unrelated to multi queries or the helper (not used in autocomplete) @bsuravech

**Comment by bsuravech** [comment]
@Haroenv weird behaviour from the engine... I wasn't able to replicate this in my other M2 environment. Do you know if this is impacting any other customers? Is this a setting perhaps in Algolia?

**Comment by Haroenv** [comment]
I have no idea, never saw it before, but 307 is a redirect, which probably explains why that shows as two network requests

**Comment by bsuravech** [comment]
Where do we define the hosts here? @Haroenv seems like we make the initial request in nonsecure

Screenshot 2021-02-11 at 11 42 01

**Comment by Haroenv** [comment]
I think client v3 takes the same protocol as the page, in v4 that's not the case.

whenever you're calling `algoliasearch` (not in this project) you can do `algoliasearch("","",{protocol: "https:"})`

**Comment by bsuravech** [comment]
Huh... I never had to add it before but adding it did correct it to use https. Why now? What's changed?

Also, thank you so much for answering my questions!

**Comment by Haroenv** [comment]
I don't think it's anything to worry about, which page was running this, can I try it somewhere?

**Comment by bsuravech** [comment]
Is it possible to replace the bundle in your M1 sandbox you made? I believe this one:

https://codesandbox.io/s/github/Haroenv/magento1-algolia-frontend-demo

**Comment by Haroenv** [comment]
yes, it's algoliaBundle.min.js in /src @bsuravech

**Comment by bsuravech** [comment]
Seems like there's a rate limit there for the sandbox. Perhaps we can schedule a time next week for a screenshare?

**Review by Haroenv — APPROVED** [review]

**Pull request merged**
